services:
  desafio:
    container_name: desafio
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     - "10090:80"
    tty: true
    environment:
      TERM: xterm
    volumes:
     - ./:/opt/desafio
    command: php artisan serve --host=0.0.0.0 --port=80
networks:
  desafio:
    external: true
    name: desafio